# Archivo que indica las herramientas y bibliotecas que usa el proyecto, 
# como Riverpod
# como los assets (sprites y sonidos) 
# o como metadatos del proyecto (nombre y versión cuando tengamos)

name: snow_party
description: "A new Flutter project."
publish_to: 'none'

environment:
  sdk: '>=3.1.0 <4.0.0' 

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.9
  flutter_lints: ^3.0.0
  web_socket_channel: ^3.0.3
  http: ^1.2.0
  flutter_secure_storage: ^9.2.2
  go_router: ^14.0.0

flutter:
  fonts:
    - family: Retro Gaming
      fonts:
        - asset: assets/images/fonts/Retro Gaming.ttf
  assets:
   # - assets/animations/
    - assets/images/board/
    - assets/images/board/casillas/
    - assets/images/characters/
    - assets/images/characters/general/
    - assets/images/characters/tablero/
   # - assets/images/items/
    - assets/images/ui/
    - assets/images/minigames/reflejos/
   # - assets/sounds/bgm/
   # - assets/sounds/sfx/
   # - assets/data/

# TODO Añadir dependencias mientras se va actualizando el código
# como por ejemplo GoRouter para navegar entre el tablero y los minijuegos